debug: true
join: '&2%player% ist zu uns gestossen.'
leave: '&c%player% hat uns verlassen.'
mysql:
  server:
    use: 'false'
    host: '127.0.0.1'
    port: '3306'
    user: 'root'
    pass: 'root'
    data: 'server'
  forum:
    use: 'false'
    host: '127.0.0.1'
    port: '3306'
    user: 'root'
    pass: 'root'
    data: 'forum'
  homepage:
    use: 'false'
    host: '127.0.0.1'
    port: '3306'
    user: 'root'
    pass: 'root'
    data: 'homepage'
  tables:
    mcjobs: 'server'
    pvprewards: 'server'
    bb1_users: 'forum'
    authme_activation: 'server'
scoreboard:
  useOnWorld:
    default: Statistik
    JumpnRun: JnR
    PvPWelt: PvP
    CreativeWelt: none
  use:
    statistik: true
    jnr: true
    pvp: true
  statistik:
    vault: true
    mcjobs: true
    foins: true
    sppoints: true
    vpoints: true
  colors:
    mcjobs: '&2'
    statistik: '&9'
    money: '&6'
    mcjobs: '&2'
    pwnfilter: '&4'
    online: '&7'
    foins: '&a'
    sparbuch: '&e'
    votes: '&d'
    spenden: '&b'
votereward:
  onWorld:
    HeimatStadt: namensschild
    FarmWelt: namensschild
    PvPFarmWelt: namensschild
    PvPWelt: smaragd
  items:
    namensschild: vp 5:name_tag 1,vp 5:saddle
    smaragd: vp 5:emerald 1
pvp:
  use: true
  onWorld:
  - PvPWelt
protect:
  onuse:
    use: true
    worlds:
    - PVPWelt
    furnace:
      use: true
      useable: '&2Der Ofen ist nun wieder Freigegeben.'
      protected: '&cDer Ofen ist nun gesichert vor Fremd Benutzung.'
      inuse: '&cDer Ofen ist bereits in verwendung von einer anderen Person.'
    brewer:
      use: true
      useable: '&2Der Braustand ist nun wieder Freigegeben.'
      protected: '&cDer Braustand ist nun gesichert vor Fremd Benutzung.'
      inuse: '&cDer Braustand ist bereits in verwendung von einer anderen Person.'
  entity:
    use: true
    list:
    - Villager
    - Irongolem
    worlds:
    - PvPWelt
    msg: '&cEs ist dir nicht erlaubt %entity% anzugreifen.'
    lightning: true
    lightning_dmg_chance: 50
mcjobs:
  save: true
  interval: 600
jumparenas:
  1:
    world: JumnRun
    min:
      x: 50
      y: 60
      z: 30
    max:
      x: 125
      y: 120
      z: 105
tw:
  list:
    world: '24h'
  interval: 5