debug: true
join: '&2%player% ist zu uns gestossen.'
leave: '&c%player% hat uns verlassen.'
mysql:
  server:
    use: 'false'
    host: '127.0.0.1'
    port: '3306'
    user: 'root'
    pass: 'root'
    data: 'server'
  forum:
    use: 'false'
    host: '127.0.0.1'
    port: '3306'
    user: 'root'
    pass: 'root'
    data: 'forum'
  homepage:
    use: 'false'
    host: '127.0.0.1'
    port: '3306'
    user: 'root'
    pass: 'root'
    data: 'homepage'
  tables:
    mcjobs: 'server'
    pvprewards: 'server'
    bb1_users: 'forum'
    authme_activation: 'server'
scoreboard:
  useOnWorld:
    default: Statistik
    JumpnRun: JnR
    PvPWelt: PvP
    CreativeWelt: none
  use:
    statistik: true
    jnr: true
    pvp: true
  statistik:
    vault: true
    mcjobs: true
    foins: true
    sppoints: true
    vpoints: true
votereward:
  onWorld:
    HeimatStadt: namensschild
    FarmWelt: namensschild
    PvPFarmWelt: namensschild
    PvPWelt: smaragd
  items:
    namensschild: vp 5:name_tag 1,vp 5:saddle
    smaragd: vp 5:emerald 1
protect:
  onuse:
    use: true
    worlds:
      - PVPWelt
    furnace:
      use: true
      useable: '&2Der Ofen ist nun wieder Freigegeben.'
      protected: '&cDer Ofen ist nun gesichert vor Fremd Benutzung.'
      inuse: '&cDer Ofen ist bereits in verwendung von einer anderen Person.'
    brewer:
      use: true
      useable: '&2Der Braustand ist nun wieder Freigegeben.'
      protected: '&cDer Braustand ist nun gesichert vor Fremd Benutzung.'
      inuse: '&cDer Braustand ist bereits in verwendung von einer anderen Person.'
  entity:
    use: true
    list:
      - Villager
      - Irongolem
    worlds:
      - PvPWelt
    msg: '&cEs ist dir nicht erlaubt %entity% anzugreifen.'
    lightning: true
    lightning_dmg_chance: 50
mcjobs:
  save: true
  interval: 600
